extends: "eslint:recommended"
parserOptions: 
  ecmaVersion: 2017

plugins: 
  - prettier
  - more-naming-conventions-leading-underscore


rules:
  no-console: 0
  no-constant-condition: ["error", { "checkLoops": false }]
  prettier/prettier: error
  more-naming-conventions-leading-underscore/snake-case-variables: 2

env:
  es6: true
  node: true